start: _requirements _req_id _source _priority _status _verif_method _dependencies _description _details

//RULES
_requirements: _HEADER_LEVEL_1 "REQUIREMENTS" _WS REQS_TEXT _WS
_req_id: _HEADER_LEVEL_2 "REQ ID" _WS REQ_ID _WS
_source: _HEADER_LEVEL_3 "SOURCE" _WS SOURCE _WS
_priority: _HEADER_LEVEL_3 "PRIORITY" _WS PRIORITY _WS
_status: _HEADER_LEVEL_3 "STATUS" _WS STATUS _WS
_verif_method: _HEADER_LEVEL_3 "VERIFICATION METHOD" _WS VERIF_METHOD _WS
_dependencies: _HEADER_LEVEL_3 "DEPENDENCIES" _WS DEPENDENCIES _WS
_description: _HEADER_LEVEL_3 "DESCRIPTION" _WS DESCRIPTION _WS
_details: _HEADER_LEVEL_3 "DETAILS" _WS DETAILS

//TERMINALS
_HEADER_LEVEL_1: "# "
_HEADER_LEVEL_2: "## "
_HEADER_LEVEL_3: "### "
_WS: WS

REQS_TEXT: /.+/
REQ_ID: ("SR."|"FR.")(DIGIT|".")+
SOURCE: /.+/
PRIORITY: /.+/
STATUS: /.+/
VERIF_METHOD: /.+/
DEPENDENCIES: /.+/
DESCRIPTION: /.+/
DETAILS: /[\s\S]/+  //\s matches all whitespace characters, including \n, \r, \t, etc. \S matches all non-whitespace characters. Together, [\s\S] matches any character.

%import common.CNAME
%import common.ESCAPED_STRING
%import common.WORD
%import common.DIGIT
%import common.LETTER
%import common.WS
%import common.WS_INLINE
%import common.NEWLINE
